pipeline {
    agent any

    environment {
        TF_VAR_env = "test"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/dev-anupsa/terraform-vm-azure.git'
            }
        }

        stage('Init') {
            steps {
                dir('test') {
                    sh 'terraform init'
                }
            }
        }

        stage('Plan') {
            steps {
                dir('test') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Apply') {
            steps {
                dir('test') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}

