pipeline {
  agent any

  environment {
    TF_IN_AUTOMATION = 'true'
  }

  stages {
    stage('Init') {
      steps {
        dir('test') {
          withCredentials([
            string(credentialsId: 'ARM_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
            string(credentialsId: 'ARM_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
            string(credentialsId: 'ARM_SUBSCRIPTION_ID', variable: 'ARM_SUBSCRIPTION_ID'),
            string(credentialsId: 'ARM_TENANT_ID', variable: 'ARM_TENANT_ID')
          ]) {
            withEnv([
              "TF_VAR_client_id=${env.ARM_CLIENT_ID}",
              "TF_VAR_client_secret=${env.ARM_CLIENT_SECRET}",
              "TF_VAR_subscription_id=${env.ARM_SUBSCRIPTION_ID}",
              "TF_VAR_tenant_id=${env.ARM_TENANT_ID}"
            ]) {
              sh 'terraform init'
            }
          }
        }
      }
    }

    stage('Plan') {
      steps {
        dir('test') {
          withCredentials([
            string(credentialsId: 'ARM_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
            string(credentialsId: 'ARM_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
            string(credentialsId: 'ARM_SUBSCRIPTION_ID', variable: 'ARM_SUBSCRIPTION_ID'),
            string(credentialsId: 'ARM_TENANT_ID', variable: 'ARM_TENANT_ID')
          ]) {
            withEnv([
              "TF_VAR_client_id=${env.ARM_CLIENT_ID}",
              "TF_VAR_client_secret=${env.ARM_CLIENT_SECRET}",
              "TF_VAR_subscription_id=${env.ARM_SUBSCRIPTION_ID}",
              "TF_VAR_tenant_id=${env.ARM_TENANT_ID}"
            ]) {
              sh 'terraform plan'
            }
          }
        }
      }
    }

    stage('Apply') {
      when {
        expression { return params.APPLY_CHANGES == true }
      }
      steps {
        dir('test') {
          withCredentials([
            string(credentialsId: 'ARM_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
            string(credentialsId: 'ARM_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
            string(credentialsId: 'ARM_SUBSCRIPTION_ID', variable: 'ARM_SUBSCRIPTION_ID'),
            string(credentialsId: 'ARM_TENANT_ID', variable: 'ARM_TENANT_ID')
          ]) {
            withEnv([
              "TF_VAR_client_id=${env.ARM_CLIENT_ID}",
              "TF_VAR_client_secret=${env.ARM_CLIENT_SECRET}",
              "TF_VAR_subscription_id=${env.ARM_SUBSCRIPTION_ID}",
              "TF_VAR_tenant_id=${env.ARM_TENANT_ID}"
            ]) {
              sh 'terraform apply -auto-approve'
            }
          }
        }
      }
    }
  }

  parameters {
    booleanParam(name: 'APPLY_CHANGES', defaultValue: false, description: 'Apply Terraform changes?')
  }
}

